import os
import re

def build_llms_full():
    llms_txt_path = 'llms.txt'
    output_path = 'llms-full.txt'
    
    if not os.path.exists(llms_txt_path):
        print(f"Error: {llms_txt_path} not found.")
        return

    with open(llms_txt_path, 'r') as f:
        content = f.read()

    # Find all links to markdown files in docs/
    doc_links = re.findall(r'\[.*?\]\((docs/.*?\.md)\)', content)
    
    full_content = []
    full_content.append("# AutoArchitect Full Documentation Context\n")
    full_content.append("> This file is automatically generated. Do not edit directly.\n")
    full_content.append(f"> Generated on: {os.popen('date -u +\"%Y-%m-%dT%H:%M:%SZ\"').read().strip()}\n\n")

    for link in doc_links:
        if os.path.exists(link):
            with open(link, 'r') as f:
                full_content.append(f"## File: {link}\n")
                full_content.append(f.read())
                full_content.append("\n---\n")
        else:
            print(f"Warning: Linked file {link} not found.")

    with open(output_path, 'w') as f:
        f.write("\n".join(full_content))
    
    print(f"Successfully built {output_path}")

if __name__ == "__main__":
    build_llms_full()
